version: '3.8'

services:
  server:
    image: ghcr.io/sirenkovladd/transactify:main
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - BBOLT_PATH=/app/data/transaction.db
      - PROTOCOL=http
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ./data:/app/data
      - ./uploads:/uploads
