CREATE TABLE IF NOT EXISTS public.settings (
    key character varying(255) NOT NULL PRIMARY KEY,
    value jsonb NOT NULL,
    updated_at timestamp with time zone DEFAULT now()
);

-- Seed with current data
-- Note: Categories from client/const.ts seem more complete than src/common.go
INSERT INTO public.settings (key, value) VALUES
('categories_map', '{
	"mobile internet": ["KOODO AIRTIME", "KOODO MOBILE"],
	"internet": ["NOVUS"],
	"food & other": [
		"SAVE ON FOODS",
		"URBAN FARE",
		"NOFRILLS JOTI''S",
		"BC LIQUOR",
		"LENA MARKET",
		"WHOLE FOODS",
		"JASMINE HALAL MEATS AND M",
		"EAST WEST MARKET",
		"PIAST BAKERY",
		"POLO FARMERS MARKET 2",
		"ORGANIC ACRES MARKET",
		"MARKET MEATS KITSILAN",
		"SEVEN SEAS FISH MARKET ON",
		"LITTLE GEM GROCERY",
		"TOP TEN PRODUCE",
		"BERRYMOBILE",
		"LEGACY LIQUOR STORE",
		"VALHALLA PURE OUTFITTERS",
		"OSYOOS PRODUCE",
		"SQ *OH SWEET DAY BAKE SH",
		"Body Energy Club",
		"Aburi Market",
		"Safeway"
	],
	"takeouts": [
		"BIG DADDY''S FISH FRY",
		"STARBUCKS",
		"LA DIPERIE",
		"MR. SUSHI MAIN STREET",
		"FOGLIFTER COFFEE ROASTERS",
		"STEGA EATERY",
		"THE WATSON",
		"BEST FALAFEL",
		"DOORDASHFATBURGER",
		"OPHELIA",
		"CANUCKS SPORTS",
		"Matchstick Riley Park",
		"PNE FOOD & BEVERAGE",
		"HUNNYBEE",
		"PUREBREAD BAKERY",
		"CULTIVATE TEA",
		"COMMODORE BALLROOM",
		"SUPERFLUX (CABANA)",
		"IRISH TIMES PUB",
		"THE BENT MAST RESTAURANT",
		"CRUST BAKERY",
		"TERRAZZO",
		"10 ACRES",
		"THE FISH STORE AT FISHER",
		"Old Country Market",
		"BARKLEY CAFE",
		"RHINO COFFEE HOUSE",
		"SQ *#B33R",
		"PLEASE BEVERAGE",
		"Small Victory Bakery",
		"VIA TEVERE MAIN ST",
		"BEAUCOUP BAKERY AND C",
		"Sq *Thierry Mt. Pleasant",
		"Holy Eucharist Cathed",
		"KOZAK",
		"UBEREATS",
		"Ellipsis",
		"Cafe Lokal",
		"Tim Hortons",
		"Coffee"
	],
	"transportation": [
		"LYFT",
		"COMPASS WEB",
		"UBER",
		"COMPASS WALK",
		"COMPASS ACCOUNT",
		"BC TRANSIT",
		"COMPASS AUTOLOAD",
		"BCF - ONLINE SALES",
		"BC, SPIRIT OF",
		"BCF-CUSTOMER SERVICE CENT",
		"Bolt"
	],
	"clothes": [
		"Bailey Nelson",
		"THE ROCKIN COWBOY",
		"WINNERSHOMESENSE",
		"KOTN",
		"TOFINO PHARMACY",
		"Lamaisonsimons",
		"STITCHERS",
		"HM CA",
		"BABATON"
	],
	"health": ["COASTAL EYE CLINIC"],
	"home goods": [
		"CANADIAN TIRE",
		"YOUR DOLLAR STORE",
		"VALUE VILLAGE",
		"MICHAELS",
		"DOLLARAMA",
		"SALARMY",
		"HCM*CARSON BOOKS INC",
		"Smart N Save",
		"The Best Shop",
		"Popeyes"
	],
	"toiletries": ["SEPHORA", "Lush"],
	"presents": [
		"PET VALU CANADA INC.",
		"APPLE.COM/CA",
		"SP DBCANADA",
		"BLUMEN FLORALS"
	],
	"haircut": ["BARBER", "HAIR"],
	"donations": [],
	"therapy": [],
	"english": [],
	"subscriptions": ["Hetzner Online Gmbh"],
	"french": [],
	"events": [
		"TICKETLEADER",
		"SEATGEEK TICKETS",
		"ROYAL BC MUSEUM",
		"FOX CABARET",
		"BOUNCE* TICKET",
		"Cineplex",
		"Eventbrite"
	],
	"travel": ["VIA RAIL/ZAW99N", "AIR CAN*", "BOOKING.COM", "Wb E-Store"],
	"london drugs": ["LONDON DRUGS", "SHOPPERS DRUG"],
	"taxAccountant": ["LILICO"],
	"film": ["Amazon Channels", "PrimeVideo", "NETFLIX"],
	"hotel": ["Hotel at"],
	"visa": ["IMMIGRATION"],
	"volleyball": ["Volleyball", "Vancouver Pb Recreatio"],
	"sports": ["CLASSPASS", "HARBOUR DANCE CENTRE", "MODO YOGA"],
	"bc hydro": ["HYDRO"],
	"insurance": ["DUUO"],
	"hobbies": ["Indigo", "THE LAB VANCOUVER"],
	"banking": [],
	"preply": ["Preply"],
	"amazon": ["AMAZON.CA"],
	"sauna": [],
	"extra": [],
	"unknown": []
}'),
('subgroup_map', '{
	"parking spot": "rent",
	"tenant insurance": "rent",
	"bc hydro": "rent",
	"internet": "rent",
	"movies": "subscriptions",
	"london drugs": "toiletries",
	"vlad": "sports",
	"dental": "health",
	"film": "hobbies",
	"books": "hobbies",
	"english": "studies",
	"french": "studies",
	"preply": "studies",
	"interest": "banking",
	"hotel": "travel"
}')
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;
